// react/src/components/MovieDetail.tsx
import { useEffect } from 'react'
import { useParams } from 'react-router-dom'
import { useMovie } from '../hooks/useMovie'

export const MovieDetail = () => {
  const { movieId } = useParams()
  const { movie, fetchMovie } = useMovie()

  useEffect(() => {
    fetchMovie(+movieId!)
  }, [])

  return (
    <>
      <div>{movie?.id}</div>
      <div>{movie?.title}</div>
      <div>{movie?.release_date}</div>
    </>
  )
}

// vue/src/components/MovieDetail.vue
<script lang="ts" setup>
import { onMounted } from 'vue';
import { useRoute } from 'vue-router';
import { useMovie } from '../composables/useMovie';

const { params: { movieId } } = useRoute()
const { movie, fetchMovie } = useMovie();

onMounted(() => fetchMovie(+movieId))

</script>
<template>
    <div>{{ movie?.id }}</div>
    <div>{{ movie?.title }}</div>
    <div>{{ movie?.release_date }}</div>
</template>
