// vue/src/App.vue
<script setup lang="ts">
import { provide } from 'vue';
import Header from './components/Header.vue';
import { UserContext, user } from './models/user'

provide(UserContext, user)

const onImageClick = () => alert('you clicked the header image!')
</script>

<template>
  <div class="app">
    <header>
      <Header @onImageClick="onImageClick" />
    </header>
    <main>
      <router-view />
    </main>
  </div>
</template>

<style>
.app {
  height: 100vh;
  display: grid;
  grid-template-rows: 5rem 1fr;
  grid-template-areas: "header" "main";
  color: white;
}

header {
  grid-area: header;
  background: #121f4a;
}

main {
  grid-area: main;
  overflow-y: scroll;
}
</style>

// react/src/App.tsx
import './App.css'
import { Route, Routes } from 'react-router-dom'
import { Header } from './components/Header'
import { MovieDetail } from './components/MovieDetail'
import { Movies } from './components/Movies'
import { user, UserContext } from './models/user'

export const App = () => {
  const onImageClick = () => alert('you clicked the header image!')

  return (
    <UserContext.Provider value={user}>
      <div className="app">
        <header>
          <Header onImageClick={onImageClick} />
        </header>
        <main>
          <Routes>
            <Route path="/" element={<Movies />}></Route>
            <Route path=":movieId" element={<MovieDetail />}></Route>
          </Routes>
        </main>
      </div>
    </UserContext.Provider>
  )
}
